controller_list:
  - name: fake_BlueRov2_controller
    type: $(arg execution_type)
    joints:
      - virtual_joint
initial:  # Define initial robot poses.
#  - group: BlueRov2
#    pose: home

  []